name: Actualizar Canales

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: |
          npm install puppeteer
          # Librería necesaria para que Chrome corra en los servidores de GitHub
          sudo apt-get install -y libgbm-dev

      - name: Ejecutar Scraper
        run: node run.js
