name: Actualizar Canales

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Puppeteer y dependencias de sistema
        run: |
          npm install puppeteer
          # Instalar dependencias necesarias para que Chrome corra en Linux
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Ejecutar Scraper Puppeteer
        run: node tu_archivo_puppeteer.js # Reemplazá con el nombre real de tu archivo
